### ISSUE TITLE
Drop Timbre dependency?

### ISSUE THREAD

**Issue by eerohele** [cmiles74/clojure-hl7-messaging-2-parser#3]
I'm considering using this library for parsing and emitting HL7. It looks like Timbre is the sole dependency, but it's only really used for demonstration in `com.nervestaple.hl7-parser.main`. `com.nervestaple.hl7-parser.parser` requires Timbre, but doesn't actually use it.

Would you be willing to consider droping the Timbre dependency and perhaps replace the uses in `com.nervestaple.hl7-parser.main` with simple `println`s? This way, Timbre wouldn't be unnecessarily brought into projects that use a different logging library.

In any case, many thanks for making this library available!

**Comment by cmiles74** [comment]
Sure, that sounds reasonable to me. 🙂  Would you like to submit a PR with this change?

**Comment by eerohele** [comment]
Certainly. I'll have a go at it tomorrow.

**Comment by cmiles74** [comment]
This looks good, I've merged in the changes. Thank you for the contribution!

I've also added some more tests and I've fixed a bug that's been on my list for a while. 😄
